### ISSUE TITLE
Release arrayfire_d as a dub package

### ISSUE THREAD

**Issue by prasunanand** [arrayfire/arrayfire-d#2]
Hi all,

I would like to release arrayfire_d ASAP as a `dub` package on https://code.dlang.org/ as my another project would use it as a dependency for GPU backend.

Is there a checklist for making a release?

**Comment by prasunanand** [comment]
@pavanky , @9prady9  : Should I release `arrayfire_d` as version `3.4.2` ?

**Comment by 9prady9** [comment]
I have couple of queries. Does the wrapper has feature parity with 3.4.2 ? If not, does `d`'s package management has a way to do pre-stable releases ?

**Comment by prasunanand** [comment]
@9prady9 I guess for a pre-stable release we can mention it as `3.4.0-alpha` or `0.1.1` . When we are assured that the release is 'stable' with all features from `3.4.2`, we will do a new release.

**Comment by 9prady9** [comment]
Okay, lets wait and see what @pavanky has to say.

**Comment by pavanky** [comment]
I don't think it should be released until there is feature compatibility.

**Comment by prasunanand** [comment]
@pavanky, What do you think about releasing an alpha?

I can check compatibility for linear algebra functions. But what about other functionalities like FFTW and Computer Vision, etc.

I feel that if we release an alpha, dlang science community would be interested in contributing.

**Comment by pavanky** [comment]
@prasunanand It is not really a d wrapper if all you are doing is calling C functions. There is no point. Anyone could just copy the include files, rename them and do what you are suggesting.

**Comment by prasunanand** [comment]
OK. I understand your concern. We will keep it on hold.
